version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "[{asctime}] #{levelname:<8} {name}:{funcName} - {message}"
    style: "{"

handlers:
  stdout:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  stderr:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr

loggers:
  bot:
    level: WARNING
    handlers: [stdout, stderr]
    propagate: false